apiVersion: apps/v1
kind: Deployment
metadata:
  name: buscarpersonas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buscarpersonas
  template:
    metadata:
      labels:
        app: buscarpersonas
    spec:
      containers:
        - name: buscarpersonas
          image: fyjo/monosgps-buscarpersonas:v1.0.0
          ports:
            - containerPort: 8082
